# Generated by Django 3.1 on 2021-01-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210118_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='memo',
        ),
    ]
